[[moreau_cuda12]]
arch = "x86_64"
git-tree-sha1 = "e8ea1bf7a6608b7c606e35fff27b320ddfd0b82a"
libc = "glibc"
os = "linux"

    [[moreau_cuda12.download]]
    sha256 = "42224d4bc58a7fae5370d326336c44b8877c285a68b576a91c2cad155506e554"
    url = "https://github.com/optimalintellect/Moreau_CUDA_jll.jl/releases/download/v0.3.1/moreau-cuda12-linux-x86_64.tar.gz"

[[moreau_cuda13]]
arch = "x86_64"
git-tree-sha1 = "e8ea1bf7a6608b7c606e35fff27b320ddfd0b82a"
libc = "glibc"
os = "linux"

    [[moreau_cuda13.download]]
    sha256 = "edbc96054e6d85ab582becbf47ae849757c7b3a1c8b8bfb992940b6418131fa4"
    url = "https://github.com/optimalintellect/Moreau_CUDA_jll.jl/releases/download/v0.3.1/moreau-cuda13-linux-x86_64.tar.gz"
